version: '3.8'

services:
  db:
    image: postgres:13-alpine3.17
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.test
    environment:
      - RDS_TEST_HOSTNAME=db
    depends_on:
      - db
    ports:
      - '3000:3000'
    command:
      - bash
      - -c
      - |
        npm run test:e2e
    volumes:
      - ./:/api/
