version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.test
    depends_on:
      - db
    ports:
      - '3000:3000'
    command:
      - bash
      - -c
      - |
        npm run test:e2e
    volumes:
      - ./:/api/
